/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DateRangeField: typeof import('./src/components/DateRangeField.vue')['default']
    DisplayMenu: typeof import('./src/components/DisplayMenu.vue')['default']
    FilterBuilder: typeof import('./src/components/FilterBuilder.vue')['default']
    GroupRequestDialog: typeof import('./src/components/GroupRequestDialog.vue')['default']
    InventoryDetailDialog: typeof import('./src/components/InventoryDetailDialog.vue')['default']
    RequestDialog: typeof import('./src/components/RequestDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    StatusPill: typeof import('./src/components/StatusPill.vue')['default']
    Toasts: typeof import('./src/components/Toasts.vue')['default']
  }
}
